### PR TITLE
mttt.py profiler

### PR DESCRIPTION
**Pull request by ghost**
To make it work, change `process.run` in solver_launcher.py to `cProfile.run('process.run()', 'time')`
Run with `./mttt_test.sh <number of processes> <output file path>`

### CODE REVIEW

**Comment by thyrgle** [comment]
As it stands there is only one line of code, but there are 8 commits with more lines of code. Is this really what you want to submit?

**Comment by ghost** [comment]
Yes, the extra lines of code were there to convert the data into readable text, but I figured out how to do it in one.

**Comment by thyrgle** [comment]
Is it possible to add a command line flag that changes `process.run` to `cProfile.run('process.run()', 'time')`?

**Comment by ghost** [comment]
Done.

**Pull request merged**
